name: Init

on: [create, workflow_dispatch]

jobs:
  initialize_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Create Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create -t "🐞 Fix game" -l bug -b "The game is broken ⚡  because it is too slow. Go to [docs/index.html](../blob/main/docs/index.html#L78) line 78 and adjust `start` and `min` properties of speed and set the to the following values:

          speed   = { start: 0.6, decrement: 0.005, min: 0.1 }"
          
